Request Process/src/objects/SW_Process_Request__c.object
<CustomObject>
    <description>A request for processing - scouring; blending or &apos;cleaning&apos;?.</description>
    <fields>
        <fullName>Expected_Input_Weight__c</fullName>
        <description>Expected input weight (used for initial request).</description>
        <label>Expected Input Weight</label>
        <precision>15</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required_Date__c</fullName>
        <label>Required Date</label>
        <type>Date</type>
    </fields>
    <label>Process Request</label>
    <nameField>
        <displayFormat>SW-{0000000}</displayFormat>
        <label>Processing Lot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Request Process/src/classes/SWProcessingMaterialEntryTest.cls
@isTest

private class SWProcessingMaterialEntryTest {    

    static testMethod void SWProcessingMaterialEntryTest () {  
            PageReference pageRef = Page.SW_Update_Process_Materials;        
            Test.setCurrentPage(pageRef);
            SW_Process_Request__c request = new SW_Process_Request__c();              
            ApexPages.StandardController controller = new ApexPages.StandardController(request);
            
        SWProcessingMaterialEntry matEntry  = new SWProcessingMaterialEntry(controller);
        matEntry.addRow();
        matEntry.removeRow();
        matEntry.save();
                
        // also test Process Request Trigger
        request.Required_Date__c = system.today();
        request.Expected_Input_Weight__c = 100;
        insert request ;
    }
    
}