Request Process/src/objects/SW_Process_Request__c.object
<CustomObject>
    <description>A request for processing - scouring; blending or &apos;cleaning&apos;?.</description>
    <fields>
        <fullName>LastStatus__c</fullName>
        <label>LastStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Request - Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Request - Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Request - Amended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Request - Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Request - Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Request - Amended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Request - Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Request - Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Processed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Request - Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Request - Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Request - Amended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Request - Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Request - Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Request - Amended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Request - Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Request - Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Processed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Request</label>
    <nameField>
        <displayFormat>SW-{0000000}</displayFormat>
        <label>Processing Lot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Request Process/src/classes/SWProcessRequestHelper.cls
global class SWProcessRequestHelper{

    WebService static void updateStatus(String vStatus, String vName) { 

        System.debug('updateStatus for vName [' + vName + '], vStatus [' + vStatus + '].');

        SW_Process_Request__c request = [Select Name, Status__c from SW_Process_Request__c where Name = :vName];
        request.LastStatus__c = request.Status__c;
        request.Status__c = vStatus;

        update request;        
    }
    
    WebService static void updateTask(String vSubject, String vRequestName, String vId) { 

        System.debug('updateTaskfor vSubject [' + vSubject + '], vRequestName[' + vRequestName + '], vId[' + vId + '].');

        Task task = [Select Subject, Status from Task where Subject = :vSubject and WhatId = :vId and status <> 'Completed'];
        task.Status = 'Completed';
        update task;

    }

    WebService static void addActvityHistory(String vSubject, String vStatus, String vWhatId) { 
    
    //ActivityHistory newActHist = new ActivityHistory();
    
    //newActHist.Subject = vSubject;
    //newActHist.setStatus(vStatus);
    //newActHist.setWhatId(vWhatId);
    
    //binding.create(new SObject[] {newActHist});
   
    }
    
    public String describeChangesOnUpdatedObject(SW_Process_Request__c newRequest, SW_Process_Request__c oldRequest) { 
	    Schema.DescribeSObjectResult  F = SW_Process_Request__c.sObjectType.getDescribe();
      
    	// Obtaining the field name/token map for the Contact object
    	Map<String,Schema.SObjectField> fieldMap = Schema.SObjectType.SW_Process_Request__c.fields.getMap();
   		// Schema.DescribeSObjectResult objSchema = Account.sObjectType.getDescribe();
        // Map<String, Schema.SObjectField> fieldMap = objSchema.fields.getMap();


		String ret = '';
        for (String fieldName : fieldMap.keySet()){
			if(fieldName <> 'systemmodstamp' && fieldName <> 'lastmodifieddate' && fieldName <> 'Status__c' 
				&& fieldName <> 'LastStatus__c' && fieldName <> 'lastmodifiedbyid'  ){
				
	            System.debug('*** field name is ' + fieldName);   
	            Object oldVal = oldRequest.get(fieldName);
	            Object newVal = newRequest.get(fieldName);
	            
	            System.debug('*** old field value is ' + oldVal);
	            System.debug('*** new field value is ' + newVal);
	            
	            
	            if(newVal <> oldVal ){
	            	sObjectField field = fieldMap.get(fieldName);
	            	ret = ret + 'Field: [' + field.getDescribe().getLabel() + '] amended from [' + oldVal + '] to [' + newVal + '].\n';
	            	
	            }
        	}
            
        }

		return ret;
		
    }
    
   
}